elasticsearch5-ami:
        packer build -only=amazon-ebs -var-file=variables.json elasticsearch5-node.packer.json

kibana5-ami:
        packer build -only=amazon-ebs -var-file=variables.json kibana5-node.packer.json

elasticsearch6-ami:
        packer build -only=amazon-ebs -var-file=variables.json elasticsearch6-node.packer.json
        
kibana6-ami:
        packer build -only=amazon-ebs -var-file=variables.json kibana6-node.packer.json
