elasticsearch-ami:
        packer build -only=amazon-ebs -var-file=variables.json elasticsearch-node.packer.json

kibana-ami:
        packer build -only=amazon-ebs -var-file=variables.json kibana-node.packer.json
